### ISSUE TITLE
npm install warnings about typings deprecation

### ISSUE THREAD

**Issue by paullang** [paullang/angular2-quickstart#1]
When running npm install, I see the following warnings

typings WARN deprecated 9/15/2016: "registry:dt/node#6.0.0+20160909174046" is deprecated (updated, replaced or removed)
typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160725163759" is deprecated (updated, replaced or removed)

**Comment by 3du4** [comment]
I am having the same warning.

**Comment by santoslluis** [comment]
I had the same warning, and after some search I found this:
https://api.typings.org/entries/dt/core-js/versions/latest
https://api.typings.org/entries/dt/node/versions/latest

it will show you the latest tag for node and core-js to avoid this warning
now is: `node#6.0.0+20160928143418` and `core-js#0.0.0+20160914114559`

**Comment by 3du4** [comment]
you can also get the list of builds using this command for node and core-js in your terminal.

typings info dt~node --versions

typings info dt~core-js --versions

**Comment by paullang** [comment]
@3du4 @santoslluis thank you for the information :)
